
include:
  - board: akdk_bt1
    shield: ver2_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
  - board: akdk_bt1
    shield: ver2_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
 
